# Generated by Django 3.1.2 on 2020-10-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_first_name', models.CharField(max_length=200)),
                ('candidate_last_name', models.CharField(max_length=200)),
                ('candidate_email_address', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('salary', models.IntegerField(default=0)),
            ],
        ),
    ]
