# Generated by Django 3.1.2 on 2020-10-26 01:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('welcomeLiteApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='user',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]

# This is the SQL version of this migration:
# BEGIN;
# --
# -- Add field user to offer
# --
# CREATE TABLE "new__welcomeLiteApp_offer" (
#     "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT, 
#     "user_id" integer NOT NULL REFERENCES "auth_user" ("id") DEFERRABLE INITIALLY DEFERRED, 
#     "candidate_first_name" varchar(200) NOT NULL, 
#     "candidate_last_name" varchar(200) NOT NULL, 
#     "candidate_email_address" varchar(200) NOT NULL, 
#     "role" varchar(200) NOT NULL, 
#     "salary" integer NOT NULL
#     );
# INSERT INTO "new__welcomeLiteApp_offer" (
#     "id", 
#     "candidate_first_name", 
#     "candidate_last_name", 
#     "candidate_email_address", 
#     "role", 
#     "salary", 
#     "user_id"
#     ) 
#     SELECT "id", "candidate_first_name", "candidate_last_name", "candidate_email_address", "role", "salary", 1 FROM "welcomeLiteApp_offer";
# DROP TABLE "welcomeLiteApp_offer";
# ALTER TABLE "new__welcomeLiteApp_offer" RENAME TO "welcomeLiteApp_offer";
# CREATE INDEX "welcomeLiteApp_offer_user_id_cb8944e6" ON "welcomeLiteApp_offer" ("user_id");
# COMMIT;